Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  Name:
    Description: The name needs to be unique per user
    Type: String


Resources:
  Cloud9Environment:
    Type: 'AWS::Cloud9::EnvironmentEC2'
    Properties:
      AutomaticStopTimeMinutes: 30
      InstanceType: 't2.micro'
      Name: !Sub '${Name}'
      SubnetId:
        Fn::ImportValue: !Sub '${EnvironmentName}-PUB1-SN'
      # Repositories:
      #     - RepositoryUrl: !Sub 'https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${RepositoryName}'
      #       PathComponent: !Sub 'codecommit/${RepositoryName}'

Outputs:

  Cloud9URL:
    Description: Cloud9 Environment
    Value:
      Fn::Join:
      - ''
      - - !Sub https://${AWS::Region}.console.aws.amazon.com/cloud9/ide/
        - !Ref 'Cloud9Environment'