Description:
  AWS does NOT currently support an Ubuntu ami EnvironmentEC2 in CloudFormation
  This is will not work as there is no IAM identity associated with it.
  Best to log into a different account and manually setup Cloud9 w/ Ubuntu

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  Name:
    Description: The name needs to be unique per user
    Type: String


Resources:
  Cloud9Environment:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      AutomaticStopTimeMinutes: 30
      InstanceType: 't2.micro'
      Name: !Sub '${Name}'
      SubnetId:
        Fn::ImportValue: alias python=python3
          !Sub '${EnvironmentName}-PUB1-SN'
      # Repositories:
      #   - PathComponent: /cfn
      #     RepositoryUrl: !GetAtt MyRepo.CloneUrlHttp

  # MyRepo:
  #   Type: "AWS::CodeCommit::Repository"
  #   Properties:
  #     RepositoryName: MyRepo
  #     RepositoryDescription: Sample Repo for Cloud9 CFN Post


Outputs:

  Cloud9URL:
    Description: Cloud9 Environment
    Value:
      Fn::Join:
      - ''
      - - !Sub https://${AWS::Region}.console.aws.amazon.com/cloud9/ide/
        - !Ref 'Cloud9Environment'
