apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: app
  name: app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: app
    spec:
      containers:
      - image: dsalazar10/cluster
        name: app
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 80
      restartPolicy: Always


